allekslar_slider_by_code:
    path: /slider-by-code/{code}
    methods: [GET]
    defaults:
        _controller: allekslar_slider.controller.slider::showAction
        _sylius:
            template: $template
            repository:
                method: ["expr:service('allekslar_slider.repository.slider')", "getOneByCode"]
                arguments: [$code]
